USE [master]
GO
/****** Object:  Database [VentasDW]    Script Date: 02/06/2017 8:36:17 ******/
CREATE DATABASE [VentasDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VentasDW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\VentasDW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VentasDW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\VentasDW_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [VentasDW] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VentasDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VentasDW] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VentasDW] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VentasDW] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VentasDW] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VentasDW] SET ARITHABORT OFF 
GO
ALTER DATABASE [VentasDW] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VentasDW] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VentasDW] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VentasDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VentasDW] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VentasDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VentasDW] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VentasDW] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VentasDW] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VentasDW] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VentasDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VentasDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VentasDW] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VentasDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VentasDW] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VentasDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VentasDW] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VentasDW] SET RECOVERY FULL 
GO
ALTER DATABASE [VentasDW] SET  MULTI_USER 
GO
ALTER DATABASE [VentasDW] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VentasDW] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VentasDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VentasDW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VentasDW] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'VentasDW', N'ON'
GO
ALTER DATABASE [VentasDW] SET QUERY_STORE = OFF
GO
USE [VentasDW]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [VentasDW]
GO
/****** Object:  Table [dbo].[DimColors]    Script Date: 02/06/2017 8:36:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimColors](
	[IdColor] [int] IDENTITY(1,1) NOT NULL,
	[Color] [nchar](10) NOT NULL,
 CONSTRAINT [PK_DimColors] PRIMARY KEY CLUSTERED 
(
	[IdColor] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DimDate]    Script Date: 02/06/2017 8:36:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimDate](
	[IdFecha] [int] IDENTITY(1,1) NOT NULL,
	[Fecha] [datetime] NOT NULL,
	[Dia] [int] NOT NULL,
	[Mes] [int] NOT NULL,
	[Anno] [int] NOT NULL,
	[Semestre] [int] NOT NULL,
	[Trimestre] [int] NOT NULL,
	[MesNombre] [nchar](10) NOT NULL,
 CONSTRAINT [PK_DimDate] PRIMARY KEY CLUSTERED 
(
	[IdFecha] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[DimProductos]    Script Date: 02/06/2017 8:36:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DimProductos](
	[IdProducto] [int] NOT NULL,
	[Nombre] [nchar](50) NOT NULL,
	[Descripcion] [nchar](100) NOT NULL,
	[IdColor] [int] NOT NULL,
	[Precio] [numeric](18, 2) NOT NULL,
 CONSTRAINT [PK_DimProductos] PRIMARY KEY CLUSTERED 
(
	[IdProducto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[FactVentas]    Script Date: 02/06/2017 8:36:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FactVentas](
	[IdVenta] [int] IDENTITY(1,1) NOT NULL,
	[FechaPedido] [int] NOT NULL,
	[FechaVenta] [int] NOT NULL,
	[Unidades] [int] NOT NULL,
	[Total] [int] NOT NULL,
	[IdProducto] [int] NOT NULL,
 CONSTRAINT [PK_FactVentas] PRIMARY KEY CLUSTERED 
(
	[IdVenta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[DimProductos]  WITH CHECK ADD  CONSTRAINT [FK_DimProductos_DimColors] FOREIGN KEY([IdColor])
REFERENCES [dbo].[DimColors] ([IdColor])
GO
ALTER TABLE [dbo].[DimProductos] CHECK CONSTRAINT [FK_DimProductos_DimColors]
GO
ALTER TABLE [dbo].[FactVentas]  WITH CHECK ADD  CONSTRAINT [FK_FactVentas_DimDate] FOREIGN KEY([FechaPedido])
REFERENCES [dbo].[DimDate] ([IdFecha])
GO
ALTER TABLE [dbo].[FactVentas] CHECK CONSTRAINT [FK_FactVentas_DimDate]
GO
ALTER TABLE [dbo].[FactVentas]  WITH CHECK ADD  CONSTRAINT [FK_FactVentas_DimDate1] FOREIGN KEY([FechaVenta])
REFERENCES [dbo].[DimDate] ([IdFecha])
GO
ALTER TABLE [dbo].[FactVentas] CHECK CONSTRAINT [FK_FactVentas_DimDate1]
GO
ALTER TABLE [dbo].[FactVentas]  WITH CHECK ADD  CONSTRAINT [FK_FactVentas_DimProductos] FOREIGN KEY([IdProducto])
REFERENCES [dbo].[DimProductos] ([IdProducto])
GO
ALTER TABLE [dbo].[FactVentas] CHECK CONSTRAINT [FK_FactVentas_DimProductos]
GO
USE [master]
GO
ALTER DATABASE [VentasDW] SET  READ_WRITE 
GO
